enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  user/themes/quark/images/logo/logo2.png:
    name: logo2.png
    type: image/png
    size: 32595
    path: user/themes/quark/images/logo/logo2.png
custom_logo_mobile:
  user/themes/quark/images/logo/logo2.png:
    name: logo2.png
    type: image/png
    size: 32595
    path: user/themes/quark/images/logo/logo2.png
